//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Parser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


    namespace OLC2_Proyecto1_201612218.src.Backend.parser;
     using OLC2_Proyecto1_201612218.src.Backend.Interprete.Utils;
     using OLC2_Proyecto1_201612218.src.Backend.Interprete.Abstracts;
     using OLC2_Proyecto1_201612218.src.Backend.Interprete.Expresiones;
     using OLC2_Proyecto1_201612218.src.Backend.Interprete.Instrucciones;
     using MiSwitch = OLC2_Proyecto1_201612218.src.Backend.Interprete.Instrucciones.Switch;
     


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ParserBaseListener : IParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.inicio"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInicio([NotNull] ParserParser.InicioContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.inicio"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInicio([NotNull] ParserParser.InicioContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.instruccionglobal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruccionglobal([NotNull] ParserParser.InstruccionglobalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.instruccionglobal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruccionglobal([NotNull] ParserParser.InstruccionglobalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.funcionMain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncionMain([NotNull] ParserParser.FuncionMainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.funcionMain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncionMain([NotNull] ParserParser.FuncionMainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.funcion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncion([NotNull] ParserParser.FuncionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.funcion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncion([NotNull] ParserParser.FuncionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.parametros"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParametros([NotNull] ParserParser.ParametrosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.parametros"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParametros([NotNull] ParserParser.ParametrosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.bloque"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBloque([NotNull] ParserParser.BloqueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.bloque"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBloque([NotNull] ParserParser.BloqueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.instruccion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruccion([NotNull] ParserParser.InstruccionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.instruccion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruccion([NotNull] ParserParser.InstruccionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.declaracion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaracion([NotNull] ParserParser.DeclaracionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.declaracion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaracion([NotNull] ParserParser.DeclaracionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.reasignacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReasignacion([NotNull] ParserParser.ReasignacionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.reasignacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReasignacion([NotNull] ParserParser.ReasignacionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.estructuraIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEstructuraIf([NotNull] ParserParser.EstructuraIfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.estructuraIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEstructuraIf([NotNull] ParserParser.EstructuraIfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.estructuraFor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEstructuraFor([NotNull] ParserParser.EstructuraForContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.estructuraFor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEstructuraFor([NotNull] ParserParser.EstructuraForContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.estructuraSwitch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEstructuraSwitch([NotNull] ParserParser.EstructuraSwitchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.estructuraSwitch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEstructuraSwitch([NotNull] ParserParser.EstructuraSwitchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.casos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCasos([NotNull] ParserParser.CasosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.casos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCasos([NotNull] ParserParser.CasosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.println"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintln([NotNull] ParserParser.PrintlnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.println"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintln([NotNull] ParserParser.PrintlnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.tipoDato"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTipoDato([NotNull] ParserParser.TipoDatoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.tipoDato"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTipoDato([NotNull] ParserParser.TipoDatoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTipo([NotNull] ParserParser.TipoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTipo([NotNull] ParserParser.TipoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp([NotNull] ParserParser.ExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp([NotNull] ParserParser.ExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.slice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSlice([NotNull] ParserParser.SliceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.slice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSlice([NotNull] ParserParser.SliceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.llamadafunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLlamadafunc([NotNull] ParserParser.LlamadafuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.llamadafunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLlamadafunc([NotNull] ParserParser.LlamadafuncContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
