//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/pamel/OneDrive/Desktop/Universidad/Compiladores22/Proyecto2/OLC2_Proyecto2_201612218/OLC2_Proyecto2_201612218/src/Backend/parser/Parser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


    namespace OLC2_Proyecto2_201612218.src.Backend.parser;
    using OLC2_Proyecto2_201612218.src.Backend.Compilador.Utils;
    using OLC2_Proyecto2_201612218.src.Backend.Compilador.Abstracts;
    using OLC2_Proyecto2_201612218.src.Backend.Compilador.Expresiones;
    using OLC2_Proyecto2_201612218.src.Backend.Compilador.Instrucciones;
    using MiSwitch = OLC2_Proyecto2_201612218.src.Backend.Compilador.Instrucciones.Switch;

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ParserParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.inicio"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInicio([NotNull] ParserParser.InicioContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.inicio"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInicio([NotNull] ParserParser.InicioContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.instruccionglobal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruccionglobal([NotNull] ParserParser.InstruccionglobalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.instruccionglobal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruccionglobal([NotNull] ParserParser.InstruccionglobalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.funcionMain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncionMain([NotNull] ParserParser.FuncionMainContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.funcionMain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncionMain([NotNull] ParserParser.FuncionMainContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.funcion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncion([NotNull] ParserParser.FuncionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.funcion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncion([NotNull] ParserParser.FuncionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.parametros"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParametros([NotNull] ParserParser.ParametrosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.parametros"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParametros([NotNull] ParserParser.ParametrosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.bloque"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBloque([NotNull] ParserParser.BloqueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.bloque"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBloque([NotNull] ParserParser.BloqueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.instruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruccion([NotNull] ParserParser.InstruccionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.instruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruccion([NotNull] ParserParser.InstruccionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaracion([NotNull] ParserParser.DeclaracionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaracion([NotNull] ParserParser.DeclaracionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.reasignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReasignacion([NotNull] ParserParser.ReasignacionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.reasignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReasignacion([NotNull] ParserParser.ReasignacionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.estructuraIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEstructuraIf([NotNull] ParserParser.EstructuraIfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.estructuraIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEstructuraIf([NotNull] ParserParser.EstructuraIfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.estructuraFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEstructuraFor([NotNull] ParserParser.EstructuraForContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.estructuraFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEstructuraFor([NotNull] ParserParser.EstructuraForContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.estructuraSwitch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEstructuraSwitch([NotNull] ParserParser.EstructuraSwitchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.estructuraSwitch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEstructuraSwitch([NotNull] ParserParser.EstructuraSwitchContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCasos([NotNull] ParserParser.CasosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCasos([NotNull] ParserParser.CasosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.println"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintln([NotNull] ParserParser.PrintlnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.println"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintln([NotNull] ParserParser.PrintlnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.tipoDato"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTipoDato([NotNull] ParserParser.TipoDatoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.tipoDato"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTipoDato([NotNull] ParserParser.TipoDatoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTipo([NotNull] ParserParser.TipoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTipo([NotNull] ParserParser.TipoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp([NotNull] ParserParser.ExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp([NotNull] ParserParser.ExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.slice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlice([NotNull] ParserParser.SliceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.slice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlice([NotNull] ParserParser.SliceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserParser.llamadafunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLlamadafunc([NotNull] ParserParser.LlamadafuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserParser.llamadafunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLlamadafunc([NotNull] ParserParser.LlamadafuncContext context);
}
